version: CI-{build}
image: Visual Studio 2019
configuration:
- Release
platform: Any CPU
init:
- ps: |- 
    if ($env:APPVEYOR_REPO_TAG -eq "true")
    {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
    }
environment:
  CODECOV_TOKEN: 
    secure: EZNjEryLzLbW2DVaHYAe7hn5ze75CctdkAzGJY9LsTMmIq9aUVTo7K4wGwveKgGU
before_build:
- ps: |-
    dotnet --version
    dotnet restore ./Source/Reloaded.Memory.Buffers.sln
after_build:
- ps: |-
    if ($env:APPVEYOR_REPO_TAG -eq "true")
    {
        echo $PWD
        $env:CHANGELOG_PATH = "CHANGELOG.MD"
        & npm install -g auto-changelog
        & auto-changelog --sort-commits date --hide-credit --template keepachangelog --commit-limit false --starting-version "$env:APPVEYOR_REPO_TAG_NAME" -o $env:CHANGELOG_PATH 
        $env:CHANGELOG_TEXT = Get-Content -Path $env:CHANGELOG_PATH -Raw
        $env:CHANGELOG_TEXT = $env:CHANGELOG_TEXT -replace "\n", "`\n"
        echo $env:CHANGELOG_TEXT
    }
build:
  project: ./Source/Reloaded.Memory.Buffers.sln
  verbosity: minimal
test_script:
- cmd: |-
    choco install codecov
    dotnet test ./Source/Reloaded.Memory.Buffers.sln /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=../../Coverage/Reloaded.Memory.Buffers.Tests.xml /p:Exclude=\"[Reloaded.Memory.Buffers.Shared]*,[xunit.*]*\"
    codecov -f "./Coverage/Reloaded.Memory.Buffers.Tests.xml"
artifacts:
- path: Source\Reloaded.Memory.Buffers\bin\Release
  name: Release Build
- path: Coverage
  name: Coverage Statistics
- path: Source\Reloaded.Memory.Buffers\bin\Release\*.nupkg
  name: Nuget Release Package
- path: $(CHANGELOG_PATH)
  name: Changelog
deploy:
- provider: GitHub
  description: |
    $(CHANGELOG_TEXT)
  auth_token:
    secure: 3nktB3Ovacl0onzwjgI+F7MtWvAzl1YMIA5gRE+vsVwKzFHICg1wKlj9O63IIiwS
  artifact: Release Build, Nuget Release Package
  on:
    APPVEYOR_REPO_TAG: true
- provider: NuGet
  api_key:
    secure: /T4vdj8lFWKOcuR5WguX5THrC1DYP4ofjy8yCdm3pz9T/yBMqEZoQKXvVzEBu965
  artifact: Nuget Release Package
  on:
    APPVEYOR_REPO_TAG: true