[build]
# Note: This breaks IntelliJ Rust. Remove this line temporarily if working from that IDE.
#target = ['x86_64-unknown-linux-gnu','x86_64-apple-darwin','x86_64-pc-windows-msvc']
#target = 'x86_64-unknown-linux-gnu' # don't commit, IntelliJ only.
#target = 'x86_64-pc-windows-msvc' # don't commit, IntelliJ only.
#target = 'x86_64-apple-darwin' # don't commit, IntelliJ only.
