name: Test in Wine

on:
  push:
    branches: [ main, crab ]
  pull_request:
    branches: [ main, crab ]
  workflow_dispatch:

jobs:
  test-native:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - id: test-rust
        uses: Reloaded-Project/reloaded-project-configurations-rust/.github/actions/test-in-wine@v1 # upgrade if needed
        with:
          rust_project_path: src-rust